# Generated by Django 4.1.7 on 2024-02-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RizalLibrary', '0002_alter_partnerlibrary_representativeemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='middleName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
