# Generated by Django 5.0.2 on 2024-04-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0008_remove_ateneoaffiliated_aainvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="visitorStatus",
            field=models.IntegerField(default=0, verbose_name=1),
        ),
    ]
