# Generated by Django 5.0.2 on 2024-04-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0009_visitor_visitorstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="visitorStatus",
            field=models.IntegerField(default=0),
        ),
    ]
