# Generated by Django 5.0.2 on 2024-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0010_alter_visitor_visitorstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ateneoaffiliated",
            name="aaVisitorID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="nonateneoaffiliated",
            name="naaVisitorID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
