# Generated by Django 5.0.2 on 2024-05-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0011_alter_ateneoaffiliated_aavisitorid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitrequest",
            name="eventPassID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RizalLibrary.event",
            ),
        ),
        migrations.AlterField(
            model_name="visitrequest",
            name="visitorID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RizalLibrary.visitor",
            ),
        ),
    ]
