# Generated by Django 5.0.2 on 2024-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0012_alter_visitrequest_eventpassid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitrequest",
            name="visitorID",
        ),
        migrations.AlterField(
            model_name="visitrequest",
            name="eventPassID",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visitrequest",
            name="VisitorID",
            field=models.IntegerField(null=True),
        ),
    ]
