# Generated by Django 5.0.2 on 2024-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0013_remove_visitrequest_visitorid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitrequest",
            old_name="VisitorID",
            new_name="visitorID",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="visitorStatus",
        ),
        migrations.RemoveField(
            model_name="visitrequestday",
            name="visitTime",
        ),
        migrations.AddField(
            model_name="visitrequestday",
            name="arrivalTime",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="visitrequestday",
            name="exitTime",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="visitrequestday",
            name="visitStatus",
            field=models.IntegerField(default=0),
        ),
    ]
