# Generated by Django 5.0.2 on 2024-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0015_alter_visitrequestday_visitrequestid"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="locationID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="otherLocationID",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
