# Generated by Django 5.0.2 on 2024-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0016_activity_locationid_activity_otherlocationid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="endPage",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="activity",
            name="startPage",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="activity",
            name="visitorRequestID",
            field=models.IntegerField(),
        ),
    ]
