# Generated by Django 5.0.2 on 2024-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0018_alter_activity_otherlocationid"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitrequest",
            name="visitRequestStatus",
            field=models.IntegerField(default=0),
        ),
    ]
