# Generated by Django 5.0.2 on 2024-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0020_alter_nonateneoaffiliated_naainvitation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonateneoaffiliated",
            name="naaInvitation",
            field=models.ImageField(upload_to="images/NAF/invitation"),
        ),
        migrations.AlterField(
            model_name="nonateneoaffiliated",
            name="naaPaymentConfirmation",
            field=models.ImageField(upload_to="images/NAF/payment"),
        ),
    ]
