# Generated by Django 5.0.2 on 2024-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0022_alter_ateneoaffiliated_aacourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ateneoaffiliated",
            name="aaCourse",
            field=models.CharField(blank=True, default="asd", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ateneoaffiliated",
            name="aaLastSem",
            field=models.CharField(blank=True, default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ateneoaffiliated",
            name="aaYear",
            field=models.IntegerField(blank=True, default=2024),
            preserve_default=False,
        ),
    ]
