# Generated by Django 5.0.2 on 2024-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0023_alter_ateneoaffiliated_aacourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="accountType",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="activity",
            name="requestPurpose",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="location",
            name="building",
            field=models.CharField(max_length=30),
        ),
    ]
