# Generated by Django 5.0.2 on 2024-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0024_alter_account_accounttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="requestPurpose",
            field=models.CharField(max_length=15),
        ),
    ]
