# Generated by Django 5.0.2 on 2024-05-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "RizalLibrary",
            "0026_alter_account_locationid_alter_activity_endpage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locationID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
