# Generated by Django 5.0.2 on 2024-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0027_alter_location_locationid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="locationID",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="otherLocationID",
        ),
        migrations.AddField(
            model_name="visitrequest",
            name="locationID",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visitrequest",
            name="eventPassID",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
