# Generated by Django 5.0.2 on 2024-05-06 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0028_remove_activity_locationid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="accountType",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="AccountMoreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locationID", models.SmallIntegerField()),
                ("accountType", models.CharField(max_length=10)),
                (
                    "baseAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
