# Generated by Django 5.0.2 on 2024-05-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0029_alter_account_accounttype_accountmoreinfo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationvisitrequest",
            name="locationID",
        ),
        migrations.RemoveField(
            model_name="locationvisitrequest",
            name="visitorRequestID",
        ),
        migrations.AlterField(
            model_name="accountmoreinfo",
            name="baseAccount",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountmoreinfo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="AccountVisitRequest",
        ),
        migrations.DeleteModel(
            name="LocationVisitRequest",
        ),
    ]
