# Generated by Django 4.1.7 on 2024-02-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarianEmail', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AteneoAffiliated',
            fields=[
                ('aaVisitorID', models.AutoField(primary_key=True, serialize=False)),
                ('aaType', models.CharField(max_length=50)),
                ('aaYear', models.IntegerField(verbose_name=4)),
                ('aaIDPhoto', models.FileField(upload_to='')),
                ('aaCourse', models.CharField(max_length=50)),
                ('aaLastSem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventPassID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('participantsNum', models.IntegerField()),
                ('pointPerson', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('librarianEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.account')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NonAteneoAffiliated',
            fields=[
                ('naaVisitorID', models.AutoField(primary_key=True, serialize=False)),
                ('naaType', models.CharField(max_length=50)),
                ('naaCompanions', models.CharField(max_length=100)),
                ('naaInvitation', models.FileField(upload_to='')),
                ('naaPaymentConfirmation', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLibrary',
            fields=[
                ('plVisitorID', models.AutoField(primary_key=True, serialize=False)),
                ('librarianName', models.CharField(max_length=100)),
                ('requestorName', models.CharField(max_length=100)),
                ('requestorEmail', models.EmailField(max_length=100)),
                ('representativeName', models.CharField(max_length=100)),
                ('representativeEmail', models.EmailField(max_length=100)),
                ('representativeID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitorID', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('visitorEmail', models.EmailField(max_length=100)),
                ('idNumber', models.IntegerField()),
                ('affiliation', models.CharField(max_length=100)),
                ('visitorType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('visitorRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('eventPassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.event')),
                ('visitorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequestDay',
            fields=[
                ('visitRequestDayID', models.AutoField(primary_key=True, serialize=False)),
                ('dateOfVisit', models.DateField()),
                ('visitTime', models.TimeField()),
                ('visitStatus', models.CharField(max_length=50)),
                ('visitRequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.visitrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LocationVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationSection', models.CharField(max_length=50)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.location')),
                ('visitorRequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.visitrequest')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='locationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.location'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('requestPurpose', models.CharField(max_length=225)),
                ('bookTitle', models.CharField(max_length=225)),
                ('startPage', models.IntegerField(verbose_name=5)),
                ('endPage', models.IntegerField(verbose_name=5)),
                ('visitorRequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.visitrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AccountVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarianEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.account')),
                ('visitRequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.visitrequest')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='locationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RizalLibrary.location'),
        ),
    ]
