# Generated by Django 5.0.2 on 2024-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RizalLibrary", "0006_alter_partnerlibrary_plvisitorid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ateneoaffiliated",
            name="aaInvitation",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="ateneoaffiliated",
            name="aaPaymentConfirmation",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="ateneoaffiliated",
            name="aaType",
            field=models.CharField(
                choices=[
                    ("ALUMNI (Admu)", "ALUMNI (Admu)"),
                    ("Basic Education Unit (BEU)", "Basic Education Unit (BEU)"),
                    ("Leave of Absence (LOA)", "Leave of Absence (LOA)"),
                ],
                default="ALUMNI (Admu)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="nonateneoaffiliated",
            name="naaInvitation",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="nonateneoaffiliated",
            name="naaPaymentConfirmation",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="nonateneoaffiliated",
            name="naaType",
            field=models.CharField(
                choices=[
                    ("Public Researcher", "Public Researcher"),
                    ("Library Guest ", "Library Guest"),
                    ("Vendor/Supplier", "Vendor/Supplier"),
                ],
                default="Library Guest ",
                max_length=50,
            ),
        ),
    ]
