# Generated by Django 5.0.2 on 2024-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RizalLibrary', '0008_remove_ateneoaffiliated_aainvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ateneoaffiliated',
            name='aaLastSem',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
